<!--<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Welcome to the <span id="zf-name">Zend Framework!</span></h1>

    <h3>This is your project's main page</h3>

    <div id="more-information">
        <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
        <p>
            Helpful Links: <br />
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a>
        </p>
    </div>
</div>-->
    <span style="background-color: #0bb20c">欢迎<?php echo $this->escape($this->username);?></span>
    <span><a href="<?php echo $this->url(array('controller'=>'index','action'=>'login')); ?>">退出</a></span>
    <p><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add')); ?>"> Add New Album</a> </p>
    <table border="1">
        <tr>
            <th>Title</th>
            <th>Artist</th>
            <th>Operation</th>
        </tr>
        <?php foreach($this->albums as $album):?>
        <tr>
            <td><?php echo $this->escape($album->title);?></td>
            <td><?php echo $this->escape($album->artist);?></td>
            <td>
                <a href="<?php echo $this->url(array('controller'=>'index','action'=>'edit', 'id'=>$album->id));?>">Edit</a>
                <a href="<?php echo $this->url(array('controller'=>'index','action'=>'delete', 'id'=>$album->id));?>">Delete</a>
            </td>
        </tr>
        <?php endforeach ?>
    </table>